// Generated by multi-json-to-ts


export interface IDraftInfoOutput_data {
  id: number;
  draftYear: number;
  rounds: number;
}

export interface IDraftInfoOutput {
  data: IDraftInfoOutput_data[];
  total: number;
}
