// Generated by multi-json-to-ts

import { ICommonLangInput } from "../Common";

export interface IDraftInfoInput extends ICommonLangInput {}

export interface IDraftInfoOutput_data {
  id: number;
  draftYear: number;
  rounds: number;
}

export interface IDraftInfoOutput {
  data: IDraftInfoOutput_data[];
  total: number;
}
