// Generated by multi-json-to-ts

export interface IMetaInfoInput {
  /**
   * Player IDs
   * Assuming a comma separated list
   */
  playerIds: string;

  /**
   * Team IDs
   * Assuming a comma separated list
   */
  teamIds: string;

  /**
   * Season states
   * Dont really know what the options are here
   * Assuming a comma separated list
   */
  seasonStates: string;
}

export interface IMetaInfoOutput_players_name {
  default: string;
}

export interface IMetaInfoOutput_players_currentTeams {
  teamId: number;
  abbrev: string;
  force: boolean;
}

export interface IMetaInfoOutput_players {
  playerId: number;
  playerSlug: string;
  actionShot: string;
  name: IMetaInfoOutput_players_name;
  currentTeams: IMetaInfoOutput_players_currentTeams[];
}
export interface IMetaInfoOutput_teams_name {
  default: string;
  fr: string;
}

export interface IMetaInfoOutput_teams {
  name: IMetaInfoOutput_teams_name;
  tricode: string;
  teamId: number;
}

export interface IMetaInfoOutput {
  players: IMetaInfoOutput_players[];
  teams: IMetaInfoOutput_teams[];
  seasonStates: unknown[];
}
