// Generated by multi-json-to-ts

export interface ISkaterLeadersOutput_data_player {
  id: number;
  currentTeamId: object;
  firstName: string;
  fullName: string;
  lastName: string;
  positionCode: string;
  sweaterNumber: number;
}

export interface ISkaterLeadersOutput_data_logos {
  id: number;
  background: string;
  endSeason: number;
  secureUrl: string;
  startSeason: number;
  teamId: number;
  url: string;
}
export interface ISkaterLeadersOutput_data_team {
  id: number;
  franchiseId: number;
  fullName: string;
  leagueId: number;
  logos: ISkaterLeadersOutput_data_logos[];
  rawTricode: string;
  triCode: string;
}

export interface ISkaterLeadersOutput_data {
  player: ISkaterLeadersOutput_data_player;
  points?: number;
  team: ISkaterLeadersOutput_data_team;
  goals?: number;
  assists?: number;
}

export interface ISkaterLeadersOutput {
  data: ISkaterLeadersOutput_data[];
  total: number;
}
