// Generated by multi-json-to-ts


export interface IDraftRankingsOutput_categories {
  id: number;
  name: string;
  consumerKey: string;
}

export interface IDraftRankingsOutput_rankings {
  lastName: string;
  firstName: string;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  lastAmateurClub?: string;
  lastAmateurLeague?: string;
  birthDate: string;
  birthCity?: string;
  birthStateProvince?: string;
  birthCountry: string;
  midtermRank?: number;
  finalRank?: number;
}

export interface IDraftRankingsOutput {
  draftYear: number;
  categoryId: number;
  categoryKey: string;
  draftYears: string;
  categories: IDraftRankingsOutput_categories[];
  rankings: IDraftRankingsOutput_rankings[];
}
