// Generated by multi-json-to-ts

export interface IDraftRankingsNowOutput_categories {
  id: number;
  name: string;
  consumerKey: string;
}

export interface IDraftRankingsNowOutput_rankings {
  lastName: string;
  firstName: string;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  lastAmateurClub?: string;
  lastAmateurLeague?: string;
  birthDate: string;
  birthCity: string;
  birthStateProvince?: string;
  birthCountry: string;
  midtermRank?: number;
  finalRank?: number;
}

export interface IDraftRankingsNowOutput {
  draftYear: number;
  categoryId: number;
  categoryKey: string;
  draftYears: string;
  categories: IDraftRankingsNowOutput_categories[];
  rankings: IDraftRankingsNowOutput_rankings[];
}
