// Generated by multi-json-to-ts

import { ICommonTeamInput } from "../Common";
import { ITeamRosterOutput } from "./TeamRoster";

export interface ITeamRosterNowInput extends ICommonTeamInput {}

export interface ITeamRosterNowOutput extends ITeamRosterOutput {}
