// Generated by multi-json-to-ts

export interface ITeamRosterNowOutput_forwards_firstName {
  default: string;
  cs?: string;
  de?: string;
  es?: string;
  fi?: string;
  sk?: string;
  sv?: string;
}
export interface ITeamRosterNowOutput_forwards_lastName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
  sv?: string;
}
export interface ITeamRosterNowOutput_forwards_birthCity {
  default: string;
  sv?: string;
  fi?: string;
  fr?: string;
  sk?: string;
  cs?: string;
  de?: string;
}
export interface ITeamRosterNowOutput_forwards_birthStateProvince {
  default: string;
  fr?: string;
  sk?: string;
  sv?: string;
}

export interface ITeamRosterNowOutput_forwards {
  id: number;
  headshot: string;
  firstName: ITeamRosterNowOutput_forwards_firstName;
  lastName: ITeamRosterNowOutput_forwards_lastName;
  sweaterNumber: number;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  heightInCentimeters: number;
  weightInKilograms: number;
  birthDate: string;
  birthCity: ITeamRosterNowOutput_forwards_birthCity;
  birthCountry: string;
  birthStateProvince?: ITeamRosterNowOutput_forwards_birthStateProvince;
}
export interface ITeamRosterNowOutput_defensemen_lastName {
  default: string;
  de?: string;
  es?: string;
  fi?: string;
  sv?: string;
}
export interface ITeamRosterNowOutput_defensemen_birthCity {
  default: string;
  sv?: string;
  fr?: string;
  cs?: string;
  de?: string;
  fi?: string;
  sk?: string;
}
export interface ITeamRosterNowOutput_defensemen_birthStateProvince {
  default: string;
  fr?: string;
  sk?: string;
}

export interface ITeamRosterNowOutput_defensemen {
  id: number;
  headshot: string;
  firstName: ITeamRosterNowOutput_forwards_firstName;
  lastName: ITeamRosterNowOutput_defensemen_lastName;
  sweaterNumber: number;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  heightInCentimeters: number;
  weightInKilograms: number;
  birthDate: string;
  birthCity: ITeamRosterNowOutput_defensemen_birthCity;
  birthCountry: string;
  birthStateProvince?: ITeamRosterNowOutput_defensemen_birthStateProvince;
}
export interface ITeamRosterNowOutput_goalies_firstName {
  default: string;
}
export interface ITeamRosterNowOutput_goalies_birthCity {
  default: string;
  cs?: string;
  sk?: string;
  sv?: string;
}

export interface ITeamRosterNowOutput_goalies {
  id: number;
  headshot: string;
  firstName: ITeamRosterNowOutput_goalies_firstName;
  lastName: ITeamRosterNowOutput_forwards_firstName;
  sweaterNumber: number;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  heightInCentimeters: number;
  weightInKilograms: number;
  birthDate: string;
  birthCity: ITeamRosterNowOutput_goalies_birthCity;
  birthCountry: string;
  birthStateProvince?: ITeamRosterNowOutput_forwards_birthStateProvince;
}

export interface ITeamRosterNowOutput {
  forwards: ITeamRosterNowOutput_forwards[];
  defensemen: ITeamRosterNowOutput_defensemen[];
  goalies: ITeamRosterNowOutput_goalies[];
}
