// Generated by multi-json-to-ts

import { ICommonTeamSeasonInput } from "../Common";

export interface ITeamRosterInput extends ICommonTeamSeasonInput {}

export interface ITeamRosterOutput_forwards_firstName {
  default: string;
  cs?: string;
  de?: string;
  es?: string;
  fi?: string;
  sk?: string;
  sv?: string;
}
export interface ITeamRosterOutput_forwards_lastName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
}
export interface ITeamRosterOutput_forwards_birthCity {
  default: string;
  fi?: string;
  sv?: string;
  cs?: string;
  sk?: string;
  de?: string;
}
export interface ITeamRosterOutput_forwards_birthStateProvince {
  default: string;
  fr?: string;
  sk?: string;
  sv?: string;
}

export interface ITeamRosterOutput_forwards {
  id: number;
  headshot: string;
  firstName: ITeamRosterOutput_forwards_firstName;
  lastName: ITeamRosterOutput_forwards_lastName;
  sweaterNumber: number;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  heightInCentimeters: number;
  weightInKilograms: number;
  birthDate: string;
  birthCity: ITeamRosterOutput_forwards_birthCity;
  birthCountry: string;
  birthStateProvince?: ITeamRosterOutput_forwards_birthStateProvince;
}
export interface ITeamRosterOutput_defensemen_lastName {
  default: string;
  fi?: string;
  sv?: string;
  cs?: string;
  sk?: string;
}
export interface ITeamRosterOutput_defensemen_birthCity {
  default: string;
  sv?: string;
  cs?: string;
  sk?: string;
  fi?: string;
  fr?: string;
}
export interface ITeamRosterOutput_defensemen_birthStateProvince {
  default: string;
  fr?: string;
  sk?: string;
}

export interface ITeamRosterOutput_defensemen {
  id: number;
  headshot: string;
  firstName: ITeamRosterOutput_forwards_lastName;
  lastName: ITeamRosterOutput_defensemen_lastName;
  sweaterNumber: number;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  heightInCentimeters: number;
  weightInKilograms: number;
  birthDate: string;
  birthCity: ITeamRosterOutput_defensemen_birthCity;
  birthCountry: string;
  birthStateProvince?: ITeamRosterOutput_defensemen_birthStateProvince;
}
export interface ITeamRosterOutput_goalies_firstName {
  default: string;
}
export interface ITeamRosterOutput_goalies_birthCity {
  default: string;
  sv?: string;
}
export interface ITeamRosterOutput_goalies_birthStateProvince {
  default: string;
  sk?: string;
}

export interface ITeamRosterOutput_goalies {
  id: number;
  headshot: string;
  firstName: ITeamRosterOutput_goalies_firstName;
  lastName: ITeamRosterOutput_goalies_firstName;
  sweaterNumber: number;
  positionCode: string;
  shootsCatches: string;
  heightInInches: number;
  weightInPounds: number;
  heightInCentimeters: number;
  weightInKilograms: number;
  birthDate: string;
  birthCity: ITeamRosterOutput_goalies_birthCity;
  birthCountry: string;
  birthStateProvince?: ITeamRosterOutput_goalies_birthStateProvince;
}

export interface ITeamRosterOutput {
  forwards: ITeamRosterOutput_forwards[];
  defensemen: ITeamRosterOutput_defensemen[];
  goalies: ITeamRosterOutput_goalies[];
}
