// Generated by multi-json-to-ts


export interface IGoalieStatsOutput_data {
  assists: number;
  gamesPlayed: number;
  gamesStarted: number;
  goalieFullName: string;
  goals: number;
  goalsAgainst: number;
  goalsAgainstAverage: number;
  lastName: string;
  losses: number;
  otLosses: number;
  penaltyMinutes: number;
  playerId: number;
  points: number;
  savePct: number;
  saves: number;
  seasonId: number;
  shootsCatches: string;
  shotsAgainst: number;
  shutouts: number;
  teamAbbrevs: string;
  ties: object;
  timeOnIce: number;
  wins: number;
}

export interface IGoalieStatsOutput {
  data: IGoalieStatsOutput_data[];
  total: number;
}
