// Generated by multi-json-to-ts

import { ICommonLangInput } from "../../Common";

export interface IGoalieStatsInput extends ICommonLangInput {
  /**
   * Goalie report
   */
  report: string;

  /**
   * isAggregate
   */
  isAggregate?: boolean;

  /**
   * isGame
   */
  isGame?: boolean;

  /**
   * factCayenneExp
   */
  factCayenneExp?: string;

  /**
   * include
   */
  include?: string;

  /**
   * exclude
   */
  exclude?: string;

  /**
   * cayenneExp
   */
  cayenneExp: string;

  /**
   * sort
   */
  sort?: string;

  /**
   * dir
   */
  dir?: string;

  /**
   * start
   */
  start?: number;

  /**
   * limit
   * A limit of -1 will return all results
   */
  limit?: number;
}

export interface IGoalieStatsOutput_data {
  assists: number;
  gamesPlayed: number;
  gamesStarted: number;
  goalieFullName: string;
  goals: number;
  goalsAgainst: number;
  goalsAgainstAverage: number;
  lastName: string;
  losses: number;
  otLosses: number;
  penaltyMinutes: number;
  playerId: number;
  points: number;
  savePct: number;
  saves: number;
  seasonId: number;
  shootsCatches: string;
  shotsAgainst: number;
  shutouts: number;
  teamAbbrevs: string;
  ties: object;
  timeOnIce: number;
  wins: number;
}

export interface IGoalieStatsOutput {
  data: IGoalieStatsOutput_data[];
  total: number;
}
