// Generated by multi-json-to-ts

import { ICommonDateInput } from "../../Common";

export interface ITvScheduleInput extends ICommonDateInput {}

export interface ITvScheduleOutput_broadcasts {
  startTime: string;
  endTime: string;
  durationSeconds: number;
  title: string;
  description: string;
  houseNumber: string;
  broadcastType: string;
  broadcastStatus: string;
  broadcastImageUrl: string;
}

export interface ITvScheduleOutput {
  date: string;
  startDate: string;
  endDate: string;
  broadcasts: ITvScheduleOutput_broadcasts[];
}
