// Generated by multi-json-to-ts


export interface ITvScheduleNowOutput_broadcasts {
  startTime: string;
  endTime: string;
  durationSeconds: number;
  title: string;
  description: string;
  houseNumber: string;
  broadcastType: string;
  broadcastStatus: string;
  broadcastImageUrl: string;
}

export interface ITvScheduleNowOutput {
  date: string;
  startDate: string;
  endDate: string;
  broadcasts: ITvScheduleNowOutput_broadcasts[];
}
