// Generated by multi-json-to-ts

import { ICommonSeasonGameTypeCategoriesLimitInput } from "../../../Common";

export interface ISkaterStatsLeadersInput extends ICommonSeasonGameTypeCategoriesLimitInput {}

export interface ISkaterStatsLeadersOutput_points_firstName {
  default: string;
}
export interface ISkaterStatsLeadersOutput_points_lastName {
  default: string;
  cs?: string;
  sk?: string;
  fi?: string;
}

export interface ISkaterStatsLeadersOutput_points {
  id: number;
  firstName: ISkaterStatsLeadersOutput_points_firstName;
  lastName: ISkaterStatsLeadersOutput_points_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: ISkaterStatsLeadersOutput_points_firstName;
  teamLogo: string;
  position: string;
  value: number;
}
export interface ISkaterStatsLeadersOutput_goals_firstName {
  default: string;
  cs?: string;
  sk?: string;
}

export interface ISkaterStatsLeadersOutput_goals {
  id: number;
  firstName: ISkaterStatsLeadersOutput_goals_firstName;
  lastName: ISkaterStatsLeadersOutput_points_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: ISkaterStatsLeadersOutput_points_firstName;
  teamLogo: string;
  position: string;
  value: number;
}
export interface ISkaterStatsLeadersOutput_assists_lastName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
}

export interface ISkaterStatsLeadersOutput_assists {
  id: number;
  firstName: ISkaterStatsLeadersOutput_points_firstName;
  lastName: ISkaterStatsLeadersOutput_assists_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: ISkaterStatsLeadersOutput_points_firstName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface ISkaterStatsLeadersOutput {
  points?: ISkaterStatsLeadersOutput_points[];
  goals?: ISkaterStatsLeadersOutput_goals[];
  assists?: ISkaterStatsLeadersOutput_assists[];
}
