// Generated by multi-json-to-ts

export interface ISkaterStatsLeadersCurrentOutput_goals_firstName {
  default: string;
  cs?: string;
  sk?: string;
}
export interface ISkaterStatsLeadersCurrentOutput_goals_lastName {
  default: string;
}

export interface ISkaterStatsLeadersCurrentOutput_goals {
  id: number;
  firstName: ISkaterStatsLeadersCurrentOutput_goals_firstName;
  lastName: ISkaterStatsLeadersCurrentOutput_goals_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: ISkaterStatsLeadersCurrentOutput_goals_lastName;
  teamLogo: string;
  position: string;
  value: number;
}
export interface ISkaterStatsLeadersCurrentOutput_assists_lastName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
}

export interface ISkaterStatsLeadersCurrentOutput_assists {
  id: number;
  firstName: ISkaterStatsLeadersCurrentOutput_goals_firstName;
  lastName: ISkaterStatsLeadersCurrentOutput_assists_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: ISkaterStatsLeadersCurrentOutput_goals_lastName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface ISkaterStatsLeadersCurrentOutput_points {
  id: number;
  firstName: ISkaterStatsLeadersCurrentOutput_goals_lastName;
  lastName: ISkaterStatsLeadersCurrentOutput_assists_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: ISkaterStatsLeadersCurrentOutput_goals_lastName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface ISkaterStatsLeadersCurrentOutput {
  goals?: ISkaterStatsLeadersCurrentOutput_goals[];
  assists?: ISkaterStatsLeadersCurrentOutput_assists[];
  points?: ISkaterStatsLeadersCurrentOutput_points[];
}
