// Generated by multi-json-to-ts

import { ICommonCategoriesLimitInput } from "../../../Common";
import { ISkaterStatsLeadersOutput } from "./SkaterStatsLeaders";

export interface ISkaterStatsLeadersCurrentInput extends ICommonCategoriesLimitInput {}

export interface ISkaterStatsLeadersCurrentOutput extends ISkaterStatsLeadersOutput {}
