// Generated by multi-json-to-ts


export interface IShiftChartsOutput_data {
  id: number;
  detailCode: number;
  duration: string;
  endTime: string;
  eventDescription: object;
  eventDetails: object;
  eventNumber: number;
  firstName: string;
  gameId: number;
  hexValue: string;
  lastName: string;
  period: number;
  playerId: number;
  shiftNumber: number;
  startTime: string;
  teamAbbrev: string;
  teamId: number;
  teamName: string;
  typeCode: number;
}

export interface IShiftChartsOutput {
  data: IShiftChartsOutput_data[];
  total: number;
}
