// Generated by multi-json-to-ts

import { ICommonYearInput } from "../Common";

export interface IPlayoffBracketInput extends ICommonYearInput {}

export interface IPlayoffBracketOutput_series_name {
  default: string;
  fr: string;
}
export interface IPlayoffBracketOutput_series_commonName {
  default: string;
}
export interface IPlayoffBracketOutput_series_topSeedTeam {
  id: number;
  abbrev: string;
  name: IPlayoffBracketOutput_series_name;
  commonName: IPlayoffBracketOutput_series_commonName;
  placeNameWithPreposition: IPlayoffBracketOutput_series_name;
  logo: string;
}

export interface IPlayoffBracketOutput_series {
  seriesUrl: string;
  seriesTitle: string;
  seriesAbbrev: string;
  seriesLetter: string;
  playoffRound: number;
  topSeedRank: number;
  topSeedRankAbbrev: string;
  topSeedWins: number;
  bottomSeedRank: number;
  bottomSeedRankAbbrev: string;
  bottomSeedWins: number;
  winningTeamId: number;
  losingTeamId: number;
  topSeedTeam: IPlayoffBracketOutput_series_topSeedTeam;
  bottomSeedTeam: IPlayoffBracketOutput_series_topSeedTeam;
  conferenceAbbrev?: string;
  conferenceName?: string;
  seriesLogo?: string;
  seriesLogoFr?: string;
}

export interface IPlayoffBracketOutput {
  bracketLogo: string;
  bracketLogoFr: string;
  series: IPlayoffBracketOutput_series[];
}
