// Generated by multi-json-to-ts

import { ICommonDateInput } from "../../Common";

export interface IScheduleCalendarInput extends ICommonDateInput {}

export interface IScheduleCalendarOutput_teams_commonName {
  default: string;
  fr?: string;
}

export interface IScheduleCalendarOutput_teams {
  id: number;
  seasonId: number;
  commonName: IScheduleCalendarOutput_teams_commonName;
  abbrev: string;
  name: IScheduleCalendarOutput_teams_commonName;
  placeNameWithPreposition: IScheduleCalendarOutput_teams_commonName;
  placeName: IScheduleCalendarOutput_teams_commonName;
  logo: string;
  darkLogo: string;
  isNhl: boolean;
  french: boolean;
}

export interface IScheduleCalendarOutput {
  endDate: string;
  nextStartDate: string;
  previousStartDate: string;
  startDate: string;
  teams: IScheduleCalendarOutput_teams[];
}
