// Generated by multi-json-to-ts

import { ICommonLangInput } from "../../Common";

export interface IGameInput extends ICommonLangInput {}

export interface IGameOutput_data {
  id: number;
  easternStartTime: string;
  gameDate: string;
  gameNumber: number;
  gameScheduleStateId: number;
  gameStateId: number;
  gameType: number;
  homeScore: number;
  homeTeamId: number;
  period: number;
  season: number;
  visitingScore: number;
  visitingTeamId: number;
}

export interface IGameOutput {
  data: IGameOutput_data[];
  total: number;
}
