// Generated by multi-json-to-ts

import { ICommonLangInput } from "../../Common";

export interface IConfigInput extends ICommonLangInput {}

export interface IConfigOutput_game {
  displayItems: string;
  resultFilters: string;
  sortKeys: string;
}
export interface IConfigOutput_summary {
  game: IConfigOutput_game;
  season: IConfigOutput_game;
}
export interface IConfigOutput_playerReportData {
  summary: IConfigOutput_summary;
  realtime: IConfigOutput_summary;
  penalties: IConfigOutput_summary;
  shootout: IConfigOutput_summary;
  bios: IConfigOutput_summary;
  shottype: IConfigOutput_summary;
  faceoffpercentages: IConfigOutput_summary;
  percentages: IConfigOutput_summary;
  scoringRates: IConfigOutput_summary;
  penaltyShots: IConfigOutput_summary;
  puckPossessions: IConfigOutput_summary;
  timeonice: IConfigOutput_summary;
  summaryshooting: IConfigOutput_summary;
  powerplay: IConfigOutput_summary;
  goalsForAgainst: IConfigOutput_summary;
  scoringpergame: IConfigOutput_summary;
  penaltykill: IConfigOutput_summary;
  faceoffwins: IConfigOutput_summary;
}
export interface IConfigOutput_goalieReportData {
  summary: IConfigOutput_summary;
  shootout: IConfigOutput_summary;
  advanced: IConfigOutput_summary;
  bios: IConfigOutput_summary;
  startedVsRelieved: IConfigOutput_summary;
  savesByStrength: IConfigOutput_summary;
  daysrest: IConfigOutput_summary;
  penaltyShots: IConfigOutput_summary;
}
export interface IConfigOutput_teamReportData {
  summary: IConfigOutput_summary;
  goalsagainstbystrength: IConfigOutput_summary;
  realtime: IConfigOutput_summary;
  penaltykilltime: IConfigOutput_summary;
  goalgames: IConfigOutput_summary;
  powerplaytime: IConfigOutput_summary;
  penalties: IConfigOutput_summary;
  shootout: IConfigOutput_summary;
  shottype: IConfigOutput_summary;
  faceoffpercentages: IConfigOutput_summary;
  percentages: IConfigOutput_summary;
  scoretrailfirst: IConfigOutput_summary;
  daysbetweengames: IConfigOutput_summary;
  outshootoutshotby: IConfigOutput_summary;
  leadingtrailing: IConfigOutput_summary;
  goalsbyperiod: IConfigOutput_summary;
  summaryshooting: IConfigOutput_summary;
  powerplay: IConfigOutput_summary;
  penaltykill: IConfigOutput_summary;
  faceoffwins: IConfigOutput_summary;
  goalsforbystrength: IConfigOutput_summary;
}

export interface IConfigOutput {
  playerReportData: IConfigOutput_playerReportData;
  goalieReportData: IConfigOutput_goalieReportData;
  teamReportData: IConfigOutput_teamReportData;
  aggregatedColumns: string;
  individualColumns: string;
}
