// Generated by multi-json-to-ts

import { ICommonTeamInput } from "../../Common";
import { IClubStatsOutput } from "./ClubStats";

export interface IClubStatsNowInput extends ICommonTeamInput {}

export interface IClubStatsNowOutput extends IClubStatsOutput {}
