// Generated by multi-json-to-ts

export interface IClubStatsNowOutput_skaters_firstName {
  default: string;
  cs?: string;
  de?: string;
  es?: string;
  fi?: string;
  sk?: string;
  sv?: string;
}
export interface IClubStatsNowOutput_skaters_lastName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
  sv?: string;
}

export interface IClubStatsNowOutput_skaters {
  playerId: number;
  headshot: string;
  firstName: IClubStatsNowOutput_skaters_firstName;
  lastName: IClubStatsNowOutput_skaters_lastName;
  positionCode: string;
  gamesPlayed: number;
  goals: number;
  assists: number;
  points: number;
  plusMinus: number;
  penaltyMinutes: number;
  powerPlayGoals: number;
  shorthandedGoals: number;
  gameWinningGoals: number;
  overtimeGoals: number;
  shots: number;
  shootingPctg: number;
  avgTimeOnIcePerGame: number;
  avgShiftsPerGame: number;
  faceoffWinPctg: number;
}
export interface IClubStatsNowOutput_goalies_firstName {
  default: string;
}

export interface IClubStatsNowOutput_goalies {
  playerId: number;
  headshot: string;
  firstName: IClubStatsNowOutput_goalies_firstName;
  lastName: IClubStatsNowOutput_goalies_firstName;
  gamesPlayed: number;
  gamesStarted: number;
  wins: number;
  losses: number;
  ties: number;
  overtimeLosses: number;
  goalsAgainstAverage: number;
  savePercentage: number;
  shotsAgainst: number;
  saves: number;
  goalsAgainst: number;
  shutouts: number;
  goals: number;
  assists: number;
  points: number;
  penaltyMinutes: number;
  timeOnIce: number;
}

export interface IClubStatsNowOutput {
  season: string;
  gameType: number;
  skaters: IClubStatsNowOutput_skaters[];
  goalies: IClubStatsNowOutput_goalies[];
}
