// Generated by multi-json-to-ts

export interface IClubScheduleWeekNowOutput_games_venue {
  default: string;
  fr?: string;
}

export interface IClubScheduleWeekNowOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IClubScheduleWeekNowOutput_games_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IClubScheduleWeekNowOutput_games_awayTeam {
  id: number;
  placeName: IClubScheduleWeekNowOutput_games_venue;
  placeNameWithPreposition: IClubScheduleWeekNowOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  awaySplitSquad: boolean;
  score?: number;
  radioLink?: string;
  airlineLink?: string;
  airlineDesc?: string;
}
export interface IClubScheduleWeekNowOutput_games_homeTeam {
  id: number;
  placeName: IClubScheduleWeekNowOutput_games_venue;
  placeNameWithPreposition: IClubScheduleWeekNowOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  homeSplitSquad: boolean;
  score?: number;
  radioLink?: string;
  airlineLink?: string;
  airlineDesc?: string;
}
export interface IClubScheduleWeekNowOutput_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IClubScheduleWeekNowOutput_games_gameOutcome {
  lastPeriodType: string;
}
export interface IClubScheduleWeekNowOutput_games_firstInitial {
  default: string;
}
export interface IClubScheduleWeekNowOutput_games_winningGoalie {
  playerId: number;
  firstInitial: IClubScheduleWeekNowOutput_games_firstInitial;
  lastName: IClubScheduleWeekNowOutput_games_firstInitial;
}

export interface IClubScheduleWeekNowOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  venue: IClubScheduleWeekNowOutput_games_venue;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IClubScheduleWeekNowOutput_games_tvBroadcasts[];
  awayTeam: IClubScheduleWeekNowOutput_games_awayTeam;
  homeTeam: IClubScheduleWeekNowOutput_games_homeTeam;
  periodDescriptor: IClubScheduleWeekNowOutput_games_periodDescriptor;
  gameOutcome?: IClubScheduleWeekNowOutput_games_gameOutcome;
  winningGoalie?: IClubScheduleWeekNowOutput_games_winningGoalie;
  winningGoalScorer?: IClubScheduleWeekNowOutput_games_winningGoalie;
  threeMinRecap?: string;
  gameCenterLink: string;
  ticketsLink?: string;
  ticketsLinkFr?: string;
}

export interface IClubScheduleWeekNowOutput {
  previousStartDate: string;
  nextStartDate: string;
  calendarUrl: string;
  clubTimezone: string;
  clubUTCOffset: string;
  games: IClubScheduleWeekNowOutput_games[];
}
