// Generated by multi-json-to-ts

export interface IClubScheduleMonthNowOutput_games_venue {
  default: string;
  fr?: string;
}

export interface IClubScheduleMonthNowOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IClubScheduleMonthNowOutput_games_placeName {
  default: string;
}
export interface IClubScheduleMonthNowOutput_games_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IClubScheduleMonthNowOutput_games_awayTeam {
  id: number;
  placeName: IClubScheduleMonthNowOutput_games_placeName;
  placeNameWithPreposition: IClubScheduleMonthNowOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  awaySplitSquad: boolean;
  score?: number;
  airlineLink?: string;
  airlineDesc?: string;
  radioLink?: string;
}
export interface IClubScheduleMonthNowOutput_games_homeTeam {
  id: number;
  placeName: IClubScheduleMonthNowOutput_games_venue;
  placeNameWithPreposition: IClubScheduleMonthNowOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  homeSplitSquad: boolean;
  score?: number;
  airlineLink?: string;
  airlineDesc?: string;
  radioLink?: string;
}
export interface IClubScheduleMonthNowOutput_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IClubScheduleMonthNowOutput_games_gameOutcome {
  lastPeriodType: string;
}
export interface IClubScheduleMonthNowOutput_games_lastName {
  default: string;
  cs?: string;
  sk?: string;
}
export interface IClubScheduleMonthNowOutput_games_winningGoalie {
  playerId: number;
  firstInitial: IClubScheduleMonthNowOutput_games_placeName;
  lastName: IClubScheduleMonthNowOutput_games_lastName;
}

export interface IClubScheduleMonthNowOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  venue: IClubScheduleMonthNowOutput_games_venue;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IClubScheduleMonthNowOutput_games_tvBroadcasts[];
  awayTeam: IClubScheduleMonthNowOutput_games_awayTeam;
  homeTeam: IClubScheduleMonthNowOutput_games_homeTeam;
  periodDescriptor: IClubScheduleMonthNowOutput_games_periodDescriptor;
  gameOutcome?: IClubScheduleMonthNowOutput_games_gameOutcome;
  winningGoalie?: IClubScheduleMonthNowOutput_games_winningGoalie;
  winningGoalScorer?: IClubScheduleMonthNowOutput_games_winningGoalie;
  gameCenterLink: string;
  threeMinRecap?: string;
  threeMinRecapFr?: string;
  ticketsLink?: string;
  ticketsLinkFr?: string;
}

export interface IClubScheduleMonthNowOutput {
  previousMonth: string;
  currentMonth: string;
  nextMonth: string;
  calendarUrl: string;
  clubTimezone: string;
  clubUTCOffset: string;
  games: IClubScheduleMonthNowOutput_games[];
}
