// Generated by multi-json-to-ts

import { ICommonTeamDateInput } from "../../Common";

export interface IClubScheduleWeekInput extends ICommonTeamDateInput {}

export interface IClubScheduleWeekOutput_games_venue {
  default: string;
}

export interface IClubScheduleWeekOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IClubScheduleWeekOutput_games_placeName {
  default: string;
  fr?: string;
}
export interface IClubScheduleWeekOutput_games_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IClubScheduleWeekOutput_games_awayTeam {
  id: number;
  placeName: IClubScheduleWeekOutput_games_placeName;
  placeNameWithPreposition: IClubScheduleWeekOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  awaySplitSquad: boolean;
  score: number;
  airlineLink?: string;
  airlineDesc?: string;
}
export interface IClubScheduleWeekOutput_games_homeTeam {
  id: number;
  placeName: IClubScheduleWeekOutput_games_venue;
  placeNameWithPreposition: IClubScheduleWeekOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  homeSplitSquad: boolean;
  score: number;
  hotelLink?: string;
  hotelDesc?: string;
  airlineLink?: string;
  airlineDesc?: string;
}
export interface IClubScheduleWeekOutput_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IClubScheduleWeekOutput_games_gameOutcome {
  lastPeriodType: string;
}
export interface IClubScheduleWeekOutput_games_winningGoalie {
  playerId: number;
  firstInitial: IClubScheduleWeekOutput_games_venue;
  lastName: IClubScheduleWeekOutput_games_venue;
}

export interface IClubScheduleWeekOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  venue: IClubScheduleWeekOutput_games_venue;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IClubScheduleWeekOutput_games_tvBroadcasts[];
  awayTeam: IClubScheduleWeekOutput_games_awayTeam;
  homeTeam: IClubScheduleWeekOutput_games_homeTeam;
  periodDescriptor: IClubScheduleWeekOutput_games_periodDescriptor;
  gameOutcome: IClubScheduleWeekOutput_games_gameOutcome;
  winningGoalie: IClubScheduleWeekOutput_games_winningGoalie;
  threeMinRecap: string;
  threeMinRecapFr?: string;
  gameCenterLink: string;
  winningGoalScorer?: IClubScheduleWeekOutput_games_winningGoalie;
}

export interface IClubScheduleWeekOutput {
  previousStartDate: string;
  nextStartDate: string;
  calendarUrl: string;
  clubTimezone: string;
  clubUTCOffset: string;
  games: IClubScheduleWeekOutput_games[];
}
