// Generated by multi-json-to-ts

import { ICommonTeamMonthInput } from "../../Common";

export interface IClubScheduleMonthInput extends ICommonTeamMonthInput {}

export interface IClubScheduleMonthOutput_games_venue {
  default: string;
}

export interface IClubScheduleMonthOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IClubScheduleMonthOutput_games_placeName {
  default: string;
  fr?: string;
}
export interface IClubScheduleMonthOutput_games_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IClubScheduleMonthOutput_games_awayTeam {
  id: number;
  placeName: IClubScheduleMonthOutput_games_placeName;
  placeNameWithPreposition: IClubScheduleMonthOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  awaySplitSquad: boolean;
  score: number;
  airlineLink?: string;
  airlineDesc?: string;
  hotelLink?: string;
  hotelDesc?: string;
}
export interface IClubScheduleMonthOutput_games_homeTeam {
  id: number;
  placeName: IClubScheduleMonthOutput_games_venue;
  placeNameWithPreposition: IClubScheduleMonthOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  homeSplitSquad: boolean;
  score: number;
  hotelLink?: string;
  hotelDesc?: string;
  airlineLink?: string;
  airlineDesc?: string;
}
export interface IClubScheduleMonthOutput_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IClubScheduleMonthOutput_games_gameOutcome {
  lastPeriodType: string;
}
export interface IClubScheduleMonthOutput_games_lastName {
  default: string;
  cs?: string;
  sk?: string;
}
export interface IClubScheduleMonthOutput_games_winningGoalie {
  playerId: number;
  firstInitial: IClubScheduleMonthOutput_games_venue;
  lastName: IClubScheduleMonthOutput_games_lastName;
}

export interface IClubScheduleMonthOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  venue: IClubScheduleMonthOutput_games_venue;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IClubScheduleMonthOutput_games_tvBroadcasts[];
  awayTeam: IClubScheduleMonthOutput_games_awayTeam;
  homeTeam: IClubScheduleMonthOutput_games_homeTeam;
  periodDescriptor: IClubScheduleMonthOutput_games_periodDescriptor;
  gameOutcome: IClubScheduleMonthOutput_games_gameOutcome;
  winningGoalie: IClubScheduleMonthOutput_games_winningGoalie;
  threeMinRecap?: string;
  threeMinRecapFr?: string;
  gameCenterLink: string;
  winningGoalScorer?: IClubScheduleMonthOutput_games_winningGoalie;
  specialEvent?: IClubScheduleMonthOutput_games_venue;
  specialEventLogo?: string;
}

export interface IClubScheduleMonthOutput {
  previousMonth: string;
  currentMonth: string;
  nextMonth: string;
  calendarUrl: string;
  clubTimezone: string;
  clubUTCOffset: string;
  games: IClubScheduleMonthOutput_games[];
}
