// Generated by multi-json-to-ts

export interface IClubScheduleNowOutput_games_venue {
  default: string;
  fr?: string;
  es?: string;
}

export interface IClubScheduleNowOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IClubScheduleNowOutput_games_placeName {
  default: string;
  fr?: string;
}
export interface IClubScheduleNowOutput_games_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IClubScheduleNowOutput_games_awayTeam {
  id: number;
  placeName: IClubScheduleNowOutput_games_placeName;
  placeNameWithPreposition: IClubScheduleNowOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  awaySplitSquad: boolean;
  score?: number;
  radioLink?: string;
  airlineLink?: string;
  airlineDesc?: string;
  hotelLink?: string;
  hotelDesc?: string;
  promoDesc?: string;
  promoLink?: string;
}
export interface IClubScheduleNowOutput_games_homeTeam {
  id: number;
  placeName: IClubScheduleNowOutput_games_placeName;
  placeNameWithPreposition: IClubScheduleNowOutput_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  homeSplitSquad: boolean;
  score?: number;
  radioLink?: string;
  hotelLink?: string;
  hotelDesc?: string;
  airlineLink?: string;
  airlineDesc?: string;
  promoLink?: string;
  promoDesc?: string;
}
export interface IClubScheduleNowOutput_games_periodDescriptor {
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IClubScheduleNowOutput_games_gameOutcome {
  lastPeriodType: string;
}
export interface IClubScheduleNowOutput_games_firstInitial {
  default: string;
}
export interface IClubScheduleNowOutput_games_lastName {
  default: string;
  cs?: string;
  sk?: string;
}
export interface IClubScheduleNowOutput_games_winningGoalie {
  playerId: number;
  firstInitial: IClubScheduleNowOutput_games_firstInitial;
  lastName: IClubScheduleNowOutput_games_lastName;
}

export interface IClubScheduleNowOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  venue: IClubScheduleNowOutput_games_venue;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IClubScheduleNowOutput_games_tvBroadcasts[];
  awayTeam: IClubScheduleNowOutput_games_awayTeam;
  homeTeam: IClubScheduleNowOutput_games_homeTeam;
  periodDescriptor: IClubScheduleNowOutput_games_periodDescriptor;
  gameOutcome?: IClubScheduleNowOutput_games_gameOutcome;
  winningGoalie?: IClubScheduleNowOutput_games_winningGoalie;
  winningGoalScorer?: IClubScheduleNowOutput_games_winningGoalie;
  gameCenterLink: string;
  threeMinRecap?: string;
  threeMinRecapFr?: string;
  ticketsLink?: string;
  ticketsLinkFr?: string;
}

export interface IClubScheduleNowOutput {
  previousSeason: number;
  currentSeason: number;
  clubTimezone: string;
  clubUTCOffset: string;
  games: IClubScheduleNowOutput_games[];
}
