// Generated by multi-json-to-ts

import { ICommonSeasonInput } from "../../Common";

export interface IPlayoffSeriesCarouselInput extends ICommonSeasonInput {}

export interface IPlayoffSeriesCarouselOutput_rounds_series_bottomSeed {
  id: number;
  abbrev: string;
  wins: number;
  logo: string;
  darkLogo: string;
}

export interface IPlayoffSeriesCarouselOutput_rounds_series {
  seriesLetter: string;
  roundNumber: number;
  seriesLabel: string;
  seriesLink: string;
  bottomSeed: IPlayoffSeriesCarouselOutput_rounds_series_bottomSeed;
  topSeed: IPlayoffSeriesCarouselOutput_rounds_series_bottomSeed;
  neededToWin: number;
  winningTeamId: number;
  losingTeamId: number;
}

export interface IPlayoffSeriesCarouselOutput_rounds {
  roundNumber: number;
  roundLabel: string;
  roundAbbrev: string;
  series: IPlayoffSeriesCarouselOutput_rounds_series[];
}

export interface IPlayoffSeriesCarouselOutput {
  seasonId: number;
  currentRound: number;
  rounds: IPlayoffSeriesCarouselOutput_rounds[];
}
