// Generated by multi-json-to-ts


export interface IComponentSeasonOutput_data {
  id: string;
  component: string;
  gameTypeId: number;
  seasonId: number;
}

export interface IComponentSeasonOutput {
  data: IComponentSeasonOutput_data[];
  total: number;
}
