// Generated by multi-json-to-ts

export interface IScoreboardNowOutput_gamesByDate_games_venue {
  default: string;
}

export interface IScoreboardNowOutput_gamesByDate_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IScoreboardNowOutput_gamesByDate_games_name {
  default: string;
  fr: string;
}
export interface IScoreboardNowOutput_gamesByDate_games_commonName {
  default: string;
  fr?: string;
}
export interface IScoreboardNowOutput_gamesByDate_games_awayTeam {
  id: number;
  name: IScoreboardNowOutput_gamesByDate_games_name;
  commonName: IScoreboardNowOutput_gamesByDate_games_commonName;
  placeNameWithPreposition: IScoreboardNowOutput_gamesByDate_games_name;
  abbrev: string;
  score?: number;
  logo: string;
  record?: string;
}
export interface IScoreboardNowOutput_gamesByDate_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}

export interface IScoreboardNowOutput_gamesByDate_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  gameCenterLink: string;
  venue: IScoreboardNowOutput_gamesByDate_games_venue;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  tvBroadcasts: IScoreboardNowOutput_gamesByDate_games_tvBroadcasts[];
  gameState: string;
  gameScheduleState: string;
  awayTeam: IScoreboardNowOutput_gamesByDate_games_awayTeam;
  homeTeam: IScoreboardNowOutput_gamesByDate_games_awayTeam;
  ticketsLink: string;
  ticketsLinkFr: string;
  period?: number;
  periodDescriptor?: IScoreboardNowOutput_gamesByDate_games_periodDescriptor;
  threeMinRecap?: string;
  threeMinRecapFr?: string;
}

export interface IScoreboardNowOutput_gamesByDate {
  date: string;
  games: IScoreboardNowOutput_gamesByDate_games[];
}

export interface IScoreboardNowOutput {
  focusedDate: string;
  focusedDateCount: number;
  gamesByDate: IScoreboardNowOutput_gamesByDate[];
}
