// Generated by multi-json-to-ts

import { ICommonLangInput } from "../../Common";

export interface IGlossaryInput extends ICommonLangInput {}

export interface IGlossaryOutput_data {
  id: number;
  abbreviation: string;
  definition: string;
  firstSeasonForStat: number;
  fullName: string;
  languageCode: string;
  lastUpdated: string;
}

export interface IGlossaryOutput {
  data: IGlossaryOutput_data[];
  total: number;
}
