// Generated by multi-json-to-ts


export interface IPlayerGameLogNowOutput_playerStatsSeasons {
  season: number;
  gameTypes: string;
}
export interface IPlayerGameLogNowOutput_gameLog_commonName {
  default: string;
}
export interface IPlayerGameLogNowOutput_gameLog_opponentCommonName {
  default: string;
  fr?: string;
}

export interface IPlayerGameLogNowOutput_gameLog {
  gameId: number;
  teamAbbrev: string;
  homeRoadFlag: string;
  gameDate: string;
  goals: number;
  assists: number;
  commonName: IPlayerGameLogNowOutput_gameLog_commonName;
  opponentCommonName: IPlayerGameLogNowOutput_gameLog_opponentCommonName;
  points: number;
  plusMinus: number;
  powerPlayGoals: number;
  powerPlayPoints: number;
  gameWinningGoals: number;
  otGoals: number;
  shots: number;
  shifts: number;
  shorthandedGoals: number;
  shorthandedPoints: number;
  opponentAbbrev: string;
  pim: number;
  toi: string;
}

export interface IPlayerGameLogNowOutput {
  seasonId: number;
  gameTypeId: number;
  playerStatsSeasons: IPlayerGameLogNowOutput_playerStatsSeasons[];
  gameLog: IPlayerGameLogNowOutput_gameLog[];
}
