// Generated by multi-json-to-ts
import { ICommonPlayerSeasonGameTypeInput } from "../../Common";

export interface IPlayerGameLogInput extends ICommonPlayerSeasonGameTypeInput {}

export interface IPlayerGameLogOutput_playerStatsSeasons {
  season: number;
  gameTypes: string;
}
export interface IPlayerGameLogOutput_gameLog_commonName {
  default: string;
}
export interface IPlayerGameLogOutput_gameLog_opponentCommonName {
  default: string;
  fr?: string;
}

export interface IPlayerGameLogOutput_gameLog {
  gameId: number;
  teamAbbrev: string;
  homeRoadFlag: string;
  gameDate: string;
  goals: number;
  assists: number;
  commonName: IPlayerGameLogOutput_gameLog_commonName;
  opponentCommonName: IPlayerGameLogOutput_gameLog_opponentCommonName;
  points: number;
  plusMinus: number;
  powerPlayGoals: number;
  powerPlayPoints: number;
  gameWinningGoals: number;
  otGoals: number;
  shots: number;
  shifts: number;
  shorthandedGoals: number;
  shorthandedPoints: number;
  opponentAbbrev: string;
  pim: number;
  toi: string;
}

export interface IPlayerGameLogOutput {
  seasonId: number;
  gameTypeId: number;
  playerStatsSeasons: IPlayerGameLogOutput_playerStatsSeasons[];
  gameLog?: IPlayerGameLogOutput_gameLog[];
}
