// Generated by multi-json-to-ts

export interface IPlayerSpotlightOutput_name {
  default: string;
}
export interface IPlayerSpotlightOutput_0 {
  playerId: number;
  name: IPlayerSpotlightOutput_name;
  playerSlug: string;
  position: string;
  sweaterNumber: number;
  teamId: number;
  headshot: string;
  teamTriCode: string;
  teamLogo: string;
  sortId: number;
}

export type IPlayerSpotlightOutput = IPlayerSpotlightOutput_0[];
