// Generated by multi-json-to-ts

export interface IPlayerSpotlightOutput_name {
  default: string;
}
export interface IPlayerSpotlightOutput_0 {
  playerId: number;
  name: IPlayerSpotlightOutput_name;
  playerSlug: string;
  position: string;
  sweaterNumber: number;
  teamId: number;
  headshot: string;
  teamTriCode: string;
  teamLogo: string;
  sortId: number;
}

export interface IPlayerSpotlightOutput {
  0: IPlayerSpotlightOutput_0;
  1: IPlayerSpotlightOutput_0;
  2: IPlayerSpotlightOutput_0;
  3: IPlayerSpotlightOutput_0;
  4: IPlayerSpotlightOutput_0;
  5: IPlayerSpotlightOutput_0;
  6: IPlayerSpotlightOutput_0;
  7: IPlayerSpotlightOutput_0;
  8: IPlayerSpotlightOutput_0;
  9: IPlayerSpotlightOutput_0;
}
