// Generated by multi-json-to-ts

export interface IPlayoffSeriesScheduleOutput_name {
  default: string;
}
export interface IPlayoffSeriesScheduleOutput_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IPlayoffSeriesScheduleOutput_conference {
  name: string;
  abbrev: string;
}
export interface IPlayoffSeriesScheduleOutput_bottomSeedTeam {
  id: number;
  name: IPlayoffSeriesScheduleOutput_name;
  abbrev: string;
  placeName: IPlayoffSeriesScheduleOutput_name;
  placeNameWithPreposition: IPlayoffSeriesScheduleOutput_placeNameWithPreposition;
  conference: IPlayoffSeriesScheduleOutput_conference;
  record: string;
  seriesWins: number;
  divisionAbbrev: string;
  seed: number;
  logo: string;
  darkLogo: string;
}

export interface IPlayoffSeriesScheduleOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IPlayoffSeriesScheduleOutput_games_placeName {
  default: string;
  fr?: string;
}
export interface IPlayoffSeriesScheduleOutput_games_awayTeam {
  id: number;
  placeName: IPlayoffSeriesScheduleOutput_games_placeName;
  placeNameWithPreposition: IPlayoffSeriesScheduleOutput_placeNameWithPreposition;
  abbrev: string;
  score: number;
}
export interface IPlayoffSeriesScheduleOutput_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IPlayoffSeriesScheduleOutput_games_seriesStatus {
  topSeedWins: number;
  bottomSeedWins: number;
}
export interface IPlayoffSeriesScheduleOutput_games_gameOutcome {
  lastPeriodType: string;
  otPeriods?: number;
}

export interface IPlayoffSeriesScheduleOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameNumber: number;
  ifNecessary: boolean;
  venue: IPlayoffSeriesScheduleOutput_name;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IPlayoffSeriesScheduleOutput_games_tvBroadcasts[];
  awayTeam: IPlayoffSeriesScheduleOutput_games_awayTeam;
  homeTeam: IPlayoffSeriesScheduleOutput_games_awayTeam;
  gameCenterLink: string;
  periodDescriptor: IPlayoffSeriesScheduleOutput_games_periodDescriptor;
  seriesStatus: IPlayoffSeriesScheduleOutput_games_seriesStatus;
  gameOutcome: IPlayoffSeriesScheduleOutput_games_gameOutcome;
}
export interface IPlayoffSeriesScheduleOutput_fullCoverageUrl {
  cs: string;
  de: string;
  sv: string;
  fi: string;
  sk: string;
  en: string;
  fr: string;
  es: string;
}

export interface IPlayoffSeriesScheduleOutput {
  round: number;
  roundAbbrev: string;
  roundLabel: string;
  seriesLetter: string;
  seriesLogo: string;
  seriesLogoFr: string;
  neededToWin: number;
  length: number;
  bottomSeedTeam: IPlayoffSeriesScheduleOutput_bottomSeedTeam;
  topSeedTeam: IPlayoffSeriesScheduleOutput_bottomSeedTeam;
  games: IPlayoffSeriesScheduleOutput_games[];
  fullCoverageUrl: IPlayoffSeriesScheduleOutput_fullCoverageUrl;
}
