// Generated by multi-json-to-ts

export interface IScheduleByDateOutput_gameWeek_games_venue {
  default: string;
  fr?: string;
  es?: string;
}

export interface IScheduleByDateOutput_gameWeek_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IScheduleByDateOutput_gameWeek_games_placeName {
  default: string;
  fr?: string;
}
export interface IScheduleByDateOutput_gameWeek_games_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IScheduleByDateOutput_gameWeek_games_awayTeam {
  id: number;
  placeName: IScheduleByDateOutput_gameWeek_games_placeName;
  placeNameWithPreposition: IScheduleByDateOutput_gameWeek_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  awaySplitSquad: boolean;
  score: number;
}
export interface IScheduleByDateOutput_gameWeek_games_homeTeam {
  id: number;
  placeName: IScheduleByDateOutput_gameWeek_games_placeName;
  placeNameWithPreposition: IScheduleByDateOutput_gameWeek_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  homeSplitSquad: boolean;
  score: number;
}
export interface IScheduleByDateOutput_gameWeek_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IScheduleByDateOutput_gameWeek_games_gameOutcome {
  lastPeriodType: string;
}
export interface IScheduleByDateOutput_gameWeek_games_firstInitial {
  default: string;
}
export interface IScheduleByDateOutput_gameWeek_games_lastName {
  default: string;
  cs?: string;
  sk?: string;
  fi?: string;
}
export interface IScheduleByDateOutput_gameWeek_games_winningGoalie {
  playerId: number;
  firstInitial: IScheduleByDateOutput_gameWeek_games_firstInitial;
  lastName: IScheduleByDateOutput_gameWeek_games_lastName;
}

export interface IScheduleByDateOutput_gameWeek_games {
  id: number;
  season: number;
  gameType: number;
  venue: IScheduleByDateOutput_gameWeek_games_venue;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IScheduleByDateOutput_gameWeek_games_tvBroadcasts[];
  awayTeam: IScheduleByDateOutput_gameWeek_games_awayTeam;
  homeTeam: IScheduleByDateOutput_gameWeek_games_homeTeam;
  periodDescriptor: IScheduleByDateOutput_gameWeek_games_periodDescriptor;
  gameOutcome: IScheduleByDateOutput_gameWeek_games_gameOutcome;
  winningGoalie: IScheduleByDateOutput_gameWeek_games_winningGoalie;
  winningGoalScorer?: IScheduleByDateOutput_gameWeek_games_winningGoalie;
  threeMinRecap?: string;
  gameCenterLink: string;
  threeMinRecapFr?: string;
  specialEvent?: IScheduleByDateOutput_gameWeek_games_placeName;
  specialEventLogo?: string;
}

export interface IScheduleByDateOutput_gameWeek {
  date: string;
  dayAbbrev: string;
  numberOfGames: number;
  games: IScheduleByDateOutput_gameWeek_games[];
}

export interface IScheduleByDateOutput {
  nextStartDate: string;
  previousStartDate: string;
  gameWeek: IScheduleByDateOutput_gameWeek[];
  preSeasonStartDate: string;
  regularSeasonStartDate: string;
  regularSeasonEndDate: string;
  playoffEndDate: string;
  numberOfGames: number;
}
