// Generated by multi-json-to-ts

export interface IScheduleNowOutput_gameWeek_games_venue {
  default: string;
  es?: string;
  fr?: string;
  cs?: string;
  fi?: string;
  sk?: string;
}

export interface IScheduleNowOutput_gameWeek_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IScheduleNowOutput_gameWeek_games_placeName {
  default: string;
  fr?: string;
}
export interface IScheduleNowOutput_gameWeek_games_placeNameWithPreposition {
  default: string;
  fr: string;
}
export interface IScheduleNowOutput_gameWeek_games_awayTeam {
  id: number;
  placeName: IScheduleNowOutput_gameWeek_games_placeName;
  placeNameWithPreposition: IScheduleNowOutput_gameWeek_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  awaySplitSquad: boolean;
  score?: number;
  radioLink?: string;
}
export interface IScheduleNowOutput_gameWeek_games_homeTeam {
  id: number;
  placeName: IScheduleNowOutput_gameWeek_games_placeName;
  placeNameWithPreposition: IScheduleNowOutput_gameWeek_games_placeNameWithPreposition;
  abbrev: string;
  logo: string;
  darkLogo: string;
  homeSplitSquad: boolean;
  score?: number;
  radioLink?: string;
}
export interface IScheduleNowOutput_gameWeek_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IScheduleNowOutput_gameWeek_games_gameOutcome {
  lastPeriodType: string;
}
export interface IScheduleNowOutput_gameWeek_games_firstInitial {
  default: string;
}
export interface IScheduleNowOutput_gameWeek_games_lastName {
  default: string;
  cs?: string;
  sk?: string;
}
export interface IScheduleNowOutput_gameWeek_games_winningGoalie {
  playerId: number;
  firstInitial: IScheduleNowOutput_gameWeek_games_firstInitial;
  lastName: IScheduleNowOutput_gameWeek_games_lastName;
}

export interface IScheduleNowOutput_gameWeek_games {
  id: number;
  season: number;
  gameType: number;
  venue: IScheduleNowOutput_gameWeek_games_venue;
  neutralSite: boolean;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  gameState: string;
  gameScheduleState: string;
  tvBroadcasts: IScheduleNowOutput_gameWeek_games_tvBroadcasts[];
  awayTeam: IScheduleNowOutput_gameWeek_games_awayTeam;
  homeTeam: IScheduleNowOutput_gameWeek_games_homeTeam;
  periodDescriptor: IScheduleNowOutput_gameWeek_games_periodDescriptor;
  gameOutcome?: IScheduleNowOutput_gameWeek_games_gameOutcome;
  winningGoalie?: IScheduleNowOutput_gameWeek_games_winningGoalie;
  winningGoalScorer?: IScheduleNowOutput_gameWeek_games_winningGoalie;
  threeMinRecap?: string;
  gameCenterLink: string;
  threeMinRecapFr?: string;
  ticketsLink?: string;
  ticketsLinkFr?: string;
  specialEvent?: IScheduleNowOutput_gameWeek_games_firstInitial;
  specialEventLogo?: string;
}

export interface IScheduleNowOutput_gameWeek {
  date: string;
  dayAbbrev: string;
  numberOfGames: number;
  games: IScheduleNowOutput_gameWeek_games[];
}

export interface IScheduleNowOutput_oddsPartners {
  partnerId: number;
  country: string;
  name: string;
  imageUrl: string;
  siteUrl?: string;
  bgColor: string;
  textColor: string;
  accentColor: string;
}

export interface IScheduleNowOutput {
  nextStartDate: string;
  previousStartDate: string;
  gameWeek: IScheduleNowOutput_gameWeek[];
  oddsPartners: IScheduleNowOutput_oddsPartners[];
  preSeasonStartDate: string;
  regularSeasonStartDate: string;
  regularSeasonEndDate: string;
  playoffEndDate: string;
  numberOfGames: number;
}
