// Generated by multi-json-to-ts


export interface IStandingsSeasonOutput_seasons {
  id: number;
  conferencesInUse: boolean;
  divisionsInUse: boolean;
  pointForOTlossInUse: boolean;
  regulationWinsInUse: boolean;
  rowInUse: boolean;
  standingsEnd: string;
  standingsStart: string;
  tiesInUse: boolean;
  wildcardInUse: boolean;
}

export interface IStandingsSeasonOutput {
  currentDate: string;
  seasons: IStandingsSeasonOutput_seasons[];
}
