// Generated by multi-json-to-ts

import { GAME_TYPE, ICommonGameIdInput } from "../../Common";

export interface IGameStoryInput extends ICommonGameIdInput {}

export interface IGameStoryOutput_venue {
  default: string;
}

export interface IGameStoryOutput_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IGameStoryOutput_placeName {
  default: string;
  fr?: string;
}
export interface IGameStoryOutput_awayTeam {
  id: number;
  name: IGameStoryOutput_venue;
  abbrev: string;
  placeName: IGameStoryOutput_placeName;
  score: number;
  sog: number;
  logo: string;
}
export interface IGameStoryOutput_scoring_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IGameStoryOutput_scoring_goals_firstName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
}
export interface IGameStoryOutput_scoring_goals_lastName {
  default: string;
  cs?: string;
  sk?: string;
}
export interface IGameStoryOutput_scoring_goals_name {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
  sv?: string;
}
export interface IGameStoryOutput_scoring_goals_assists_lastName {
  default: string;
  cs?: string;
  de?: string;
  fi?: string;
  sk?: string;
  sv?: string;
}

export interface IGameStoryOutput_scoring_goals_assists {
  playerId: number;
  firstName: IGameStoryOutput_scoring_goals_firstName;
  lastName: IGameStoryOutput_scoring_goals_assists_lastName;
  name: IGameStoryOutput_scoring_goals_assists_lastName;
  assistsToDate: number;
}

export interface IGameStoryOutput_scoring_goals {
  situationCode: string;
  strength: string;
  playerId: number;
  firstName: IGameStoryOutput_scoring_goals_firstName;
  lastName: IGameStoryOutput_scoring_goals_lastName;
  name: IGameStoryOutput_scoring_goals_name;
  teamAbbrev: IGameStoryOutput_venue;
  headshot: string;
  highlightClipSharingUrl?: string;
  highlightClip?: number;
  goalsToDate: number;
  awayScore: number;
  homeScore: number;
  leadingTeamAbbrev?: IGameStoryOutput_venue;
  timeInPeriod: string;
  shotType: string;
  goalModifier: string;
  assists: IGameStoryOutput_scoring_goals_assists[];
  discreteClip?: number;
}

export interface IGameStoryOutput_scoring {
  periodDescriptor: IGameStoryOutput_scoring_periodDescriptor;
  goals: IGameStoryOutput_scoring_goals[];
}

export interface IGameStoryOutput_shootout {
  sequence: number;
  playerId: number;
  teamAbbrev: string;
  firstName: string;
  lastName: string;
  shotType: string;
  result: string;
  headshot: string;
  gameWinner: boolean;
}

export interface IGameStoryOutput_threeStars {
  star: number;
  playerId: number;
  teamAbbrev: string;
  headshot: string;
  name: string;
  sweaterNo: number;
  position: string;
  goalsAgainstAverage?: number;
  savePctg?: number;
  goals?: number;
  assists?: number;
  points?: number;
}

export interface IGameStoryOutput_teamGameStats {
  category: string;
  awayValue: number;
  homeValue: number;
}
export interface IGameStoryOutput_summary {
  scoring: IGameStoryOutput_scoring[];
  shootout: IGameStoryOutput_shootout[];
  threeStars: IGameStoryOutput_threeStars[];
  teamGameStats: IGameStoryOutput_teamGameStats[];
}
export interface IGameStoryOutput_clock {
  timeRemaining: string;
  secondsRemaining: number;
  running: boolean;
  inIntermission: boolean;
}

export interface IGameStoryOutput {
  id: number;
  season: number;
  gameType: GAME_TYPE;
  limitedScoring: boolean;
  gameDate: string;
  venue: IGameStoryOutput_venue;
  venueLocation: IGameStoryOutput_venue;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  venueTimezone: string;
  tvBroadcasts: IGameStoryOutput_tvBroadcasts[];
  gameState: string;
  gameScheduleState: string;
  awayTeam: IGameStoryOutput_awayTeam;
  homeTeam: IGameStoryOutput_awayTeam;
  shootoutInUse: boolean;
  maxPeriods: number;
  regPeriods: number;
  otInUse: boolean;
  tiesInUse: boolean;
  summary: IGameStoryOutput_summary;
  periodDescriptor: IGameStoryOutput_scoring_periodDescriptor;
  clock: IGameStoryOutput_clock;
}
