// Generated by multi-json-to-ts


export interface ITeamStatsOutput_data {
  faceoffWinPct: number;
  gamesPlayed: number;
  goalsAgainst: number;
  goalsAgainstPerGame: number;
  goalsFor: number;
  goalsForPerGame: number;
  losses: number;
  otLosses: number;
  penaltyKillNetPct: number;
  penaltyKillPct: number;
  pointPct: number;
  points: number;
  powerPlayNetPct: number;
  powerPlayPct: number;
  regulationAndOtWins: number;
  seasonId: number;
  shotsAgainstPerGame: number;
  shotsForPerGame: number;
  teamFullName: string;
  teamId: number;
  ties: object;
  wins: number;
  winsInRegulation: number;
  winsInShootout: number;
}

export interface ITeamStatsOutput {
  data: ITeamStatsOutput_data[];
  total: number;
}
