// Generated by multi-json-to-ts

import { ICommonLangInput } from "../../Common";

export interface ITeamStatsInput extends ICommonLangInput {
  /**
   * Team report
   */
  report: string;

  /**
   * isAggregate
   */
  isAggregate?: boolean;

  /**
   * isGame
   */
  isGame?: boolean;

  /**
   * factCayenneExp
   */
  factCayenneExp?: string;

  /**
   * include
   */
  include?: string;

  /**
   * exclude
   */
  exclude?: string;

  /**
   * cayenneExp
   */
  cayenneExp?: string;

  /**
   * sort
   */
  sort?: string;

  /**
   * dir
   */
  dir?: string;

  /**
   * start
   */
  start?: number;

  /**
   * limit
   * A limit of -1 will return all results
   */
  limit?: number;
}

export interface ITeamStatsOutput_data {
  faceoffWinPct: number;
  gamesPlayed: number;
  goalsAgainst: number;
  goalsAgainstPerGame: number;
  goalsFor: number;
  goalsForPerGame: number;
  losses: number;
  otLosses: number;
  penaltyKillNetPct: number;
  penaltyKillPct: number;
  pointPct: number;
  points: number;
  powerPlayNetPct: number;
  powerPlayPct: number;
  regulationAndOtWins: number;
  seasonId: number;
  shotsAgainstPerGame: number;
  shotsForPerGame: number;
  teamFullName: string;
  teamId: number;
  ties: object;
  wins: number;
  winsInRegulation: number;
  winsInShootout: number;
}

export interface ITeamStatsOutput {
  data: ITeamStatsOutput_data[];
  total: number;
}
