// Generated by multi-json-to-ts

import { ICommonLangInput } from "../../Common";

export interface IPlayersInput extends ICommonLangInput {}

export interface IPlayersOutput_data {
  id: number;
  currentTeamId: object;
  firstName: string;
  fullName: string;
  lastName: string;
  positionCode: string;
  sweaterNumber: object;
}

export interface IPlayersOutput {
  data: IPlayersOutput_data[];
  total: number;
}
