// Generated by multi-json-to-ts

export interface IGoalieStatsLeadersOutput_wins_firstName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
}
export interface IGoalieStatsLeadersOutput_wins_teamName {
  default: string;
}

export interface IGoalieStatsLeadersOutput_wins {
  id: number;
  firstName: IGoalieStatsLeadersOutput_wins_firstName;
  lastName: IGoalieStatsLeadersOutput_wins_firstName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}
export interface IGoalieStatsLeadersOutput_shutouts_firstName {
  default: string;
  cs?: string;
  sk?: string;
}
export interface IGoalieStatsLeadersOutput_shutouts_lastName {
  default: string;
  cs?: string;
  sk?: string;
  fi?: string;
}

export interface IGoalieStatsLeadersOutput_shutouts {
  id: number;
  firstName: IGoalieStatsLeadersOutput_shutouts_firstName;
  lastName: IGoalieStatsLeadersOutput_shutouts_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface IGoalieStatsLeadersOutput_savePctg {
  id: number;
  firstName: IGoalieStatsLeadersOutput_wins_firstName;
  lastName: IGoalieStatsLeadersOutput_shutouts_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface IGoalieStatsLeadersOutput_goalsAgainstAverage {
  id: number;
  firstName: IGoalieStatsLeadersOutput_shutouts_firstName;
  lastName: IGoalieStatsLeadersOutput_shutouts_lastName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface IGoalieStatsLeadersOutput {
  wins: IGoalieStatsLeadersOutput_wins[];
  shutouts: IGoalieStatsLeadersOutput_shutouts[];
  savePctg: IGoalieStatsLeadersOutput_savePctg[];
  goalsAgainstAverage: IGoalieStatsLeadersOutput_goalsAgainstAverage[];
}
