// Generated by multi-json-to-ts

import { ICommonCategoriesLimitInput } from "../../../Common";
import { IGoalieStatsLeadersOutput } from "./GoalieStatsLeaders";

export interface IGoalieStatsLeadersCurrentInput extends ICommonCategoriesLimitInput {}

export interface IGoalieStatsLeadersCurrentOutput extends IGoalieStatsLeadersOutput {}
