// Generated by multi-json-to-ts

export interface IGoalieStatsLeadersCurrentOutput_wins_firstName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
}
export interface IGoalieStatsLeadersCurrentOutput_wins_teamName {
  default: string;
}

export interface IGoalieStatsLeadersCurrentOutput_wins {
  id: number;
  firstName: IGoalieStatsLeadersCurrentOutput_wins_firstName;
  lastName: IGoalieStatsLeadersCurrentOutput_wins_firstName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersCurrentOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}
export interface IGoalieStatsLeadersCurrentOutput_shutouts_firstName {
  default: string;
  cs?: string;
  sk?: string;
}

export interface IGoalieStatsLeadersCurrentOutput_shutouts {
  id: number;
  firstName: IGoalieStatsLeadersCurrentOutput_shutouts_firstName;
  lastName: IGoalieStatsLeadersCurrentOutput_shutouts_firstName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersCurrentOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface IGoalieStatsLeadersCurrentOutput_savePctg {
  id: number;
  firstName: IGoalieStatsLeadersCurrentOutput_wins_firstName;
  lastName: IGoalieStatsLeadersCurrentOutput_wins_teamName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersCurrentOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface IGoalieStatsLeadersCurrentOutput_goalsAgainstAverage {
  id: number;
  firstName: IGoalieStatsLeadersCurrentOutput_shutouts_firstName;
  lastName: IGoalieStatsLeadersCurrentOutput_shutouts_firstName;
  sweaterNumber: number;
  headshot: string;
  teamAbbrev: string;
  teamName: IGoalieStatsLeadersCurrentOutput_wins_teamName;
  teamLogo: string;
  position: string;
  value: number;
}

export interface IGoalieStatsLeadersCurrentOutput {
  wins: IGoalieStatsLeadersCurrentOutput_wins[];
  shutouts: IGoalieStatsLeadersCurrentOutput_shutouts[];
  savePctg: IGoalieStatsLeadersCurrentOutput_savePctg[];
  goalsAgainstAverage: IGoalieStatsLeadersCurrentOutput_goalsAgainstAverage[];
}
