// Generated by multi-json-to-ts

import { ICommonLangInput } from "../../Common";

export interface IFranchisesInput extends ICommonLangInput {}

export interface IFranchisesOutput_data {
  id: number;
  fullName: string;
  teamCommonName: string;
  teamPlaceName: string;
}

export interface IFranchisesOutput {
  data: IFranchisesOutput_data[];
  total: number;
}
