// Generated by multi-json-to-ts


export interface IFranchisesOutput_data {
  id: number;
  fullName: string;
  teamCommonName: string;
  teamPlaceName: string;
}

export interface IFranchisesOutput {
  data: IFranchisesOutput_data[];
  total: number;
}
