// Generated by multi-json-to-ts


export interface IDailyScoresNowOutput_gameWeek {
  date: string;
  dayAbbrev: string;
  numberOfGames: number;
}

export interface IDailyScoresNowOutput_oddsPartners {
  partnerId: number;
  country: string;
  name: string;
  imageUrl: string;
  siteUrl?: string;
  bgColor: string;
  textColor: string;
  accentColor: string;
}
export interface IDailyScoresNowOutput_games_venue {
  default: string;
}

export interface IDailyScoresNowOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IDailyScoresNowOutput_games_awayTeam {
  id: number;
  name: IDailyScoresNowOutput_games_venue;
  abbrev: string;
  score: number;
  sog: number;
  logo: string;
}
export interface IDailyScoresNowOutput_games_clock {
  timeRemaining: string;
  secondsRemaining: number;
  running: boolean;
  inIntermission: boolean;
}
export interface IDailyScoresNowOutput_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IDailyScoresNowOutput_games_gameOutcome {
  lastPeriodType: string;
  otPeriods?: number;
}
export interface IDailyScoresNowOutput_games_goals_name {
  default: string;
  cs?: string;
  sk?: string;
}
export interface IDailyScoresNowOutput_games_goals_firstName {
  default: string;
  cs?: string;
  sk?: string;
  sv?: string;
  de?: string;
  es?: string;
  fi?: string;
}

export interface IDailyScoresNowOutput_games_goals_assists {
  playerId: number;
  name: IDailyScoresNowOutput_games_venue;
  assistsToDate: number;
}

export interface IDailyScoresNowOutput_games_goals {
  period: number;
  periodDescriptor: IDailyScoresNowOutput_games_periodDescriptor;
  timeInPeriod: string;
  playerId: number;
  name: IDailyScoresNowOutput_games_goals_name;
  firstName: IDailyScoresNowOutput_games_goals_firstName;
  lastName: IDailyScoresNowOutput_games_goals_name;
  goalModifier: string;
  assists: IDailyScoresNowOutput_games_goals_assists[];
  mugshot: string;
  teamAbbrev: string;
  goalsToDate: number;
  awayScore: number;
  homeScore: number;
  strength: string;
  highlightClipSharingUrl?: string;
  highlightClip?: number;
  discreteClip?: number;
  highlightClipSharingUrlFr?: string;
  highlightClipFr?: number;
  discreteClipFr?: number;
}

export interface IDailyScoresNowOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  venue: IDailyScoresNowOutput_games_venue;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  tvBroadcasts: IDailyScoresNowOutput_games_tvBroadcasts[];
  gameState: string;
  gameScheduleState: string;
  awayTeam: IDailyScoresNowOutput_games_awayTeam;
  homeTeam: IDailyScoresNowOutput_games_awayTeam;
  gameCenterLink: string;
  threeMinRecap?: string;
  clock: IDailyScoresNowOutput_games_clock;
  neutralSite: boolean;
  venueTimezone: string;
  period: number;
  periodDescriptor: IDailyScoresNowOutput_games_periodDescriptor;
  gameOutcome: IDailyScoresNowOutput_games_gameOutcome;
  goals: IDailyScoresNowOutput_games_goals[];
  condensedGame?: string;
  threeMinRecapFr?: string;
  condensedGameFr?: string;
}

export interface IDailyScoresNowOutput {
  prevDate: string;
  currentDate: string;
  nextDate: string;
  gameWeek: IDailyScoresNowOutput_gameWeek[];
  oddsPartners: IDailyScoresNowOutput_oddsPartners[];
  games: IDailyScoresNowOutput_games[];
}
