// Generated by multi-json-to-ts


export interface IDailyScoresByDateOutput_gameWeek {
  date: string;
  dayAbbrev: string;
  numberOfGames: number;
}

export interface IDailyScoresByDateOutput_oddsPartners {
  partnerId: number;
  country: string;
  name: string;
  imageUrl: string;
  siteUrl?: string;
  bgColor: string;
  textColor: string;
  accentColor: string;
}
export interface IDailyScoresByDateOutput_games_venue {
  default: string;
}

export interface IDailyScoresByDateOutput_games_tvBroadcasts {
  id: number;
  market: string;
  countryCode: string;
  network: string;
  sequenceNumber: number;
}
export interface IDailyScoresByDateOutput_games_awayTeam {
  id: number;
  name: IDailyScoresByDateOutput_games_venue;
  abbrev: string;
  score: number;
  sog: number;
  logo: string;
}
export interface IDailyScoresByDateOutput_games_clock {
  timeRemaining: string;
  secondsRemaining: number;
  running: boolean;
  inIntermission: boolean;
}
export interface IDailyScoresByDateOutput_games_periodDescriptor {
  number: number;
  periodType: string;
  maxRegulationPeriods: number;
}
export interface IDailyScoresByDateOutput_games_gameOutcome {
  lastPeriodType: string;
  otPeriods?: number;
}
export interface IDailyScoresByDateOutput_games_goals_name {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
}
export interface IDailyScoresByDateOutput_games_goals_firstName {
  default: string;
  cs?: string;
  fi?: string;
  sk?: string;
  de?: string;
  es?: string;
  sv?: string;
}
export interface IDailyScoresByDateOutput_games_goals_lastName {
  default: string;
  cs?: string;
  sk?: string;
  fi?: string;
}
export interface IDailyScoresByDateOutput_games_goals_assists_name {
  default: string;
  cs?: string;
  de?: string;
  fi?: string;
  sk?: string;
  sv?: string;
  es?: string;
}

export interface IDailyScoresByDateOutput_games_goals_assists {
  playerId: number;
  name: IDailyScoresByDateOutput_games_goals_assists_name;
  assistsToDate: number;
}

export interface IDailyScoresByDateOutput_games_goals {
  period: number;
  periodDescriptor: IDailyScoresByDateOutput_games_periodDescriptor;
  timeInPeriod: string;
  playerId: number;
  name: IDailyScoresByDateOutput_games_goals_name;
  firstName: IDailyScoresByDateOutput_games_goals_firstName;
  lastName: IDailyScoresByDateOutput_games_goals_lastName;
  goalModifier: string;
  assists: IDailyScoresByDateOutput_games_goals_assists[];
  mugshot: string;
  teamAbbrev: string;
  goalsToDate: number;
  awayScore: number;
  homeScore: number;
  strength: string;
  highlightClipSharingUrl?: string;
  highlightClip?: number;
  highlightClipSharingUrlFr?: string;
  highlightClipFr?: number;
}
export interface IDailyScoresByDateOutput_games_specialEvent {
  default: string;
  fr: string;
}

export interface IDailyScoresByDateOutput_games {
  id: number;
  season: number;
  gameType: number;
  gameDate: string;
  venue: IDailyScoresByDateOutput_games_venue;
  startTimeUTC: string;
  easternUTCOffset: string;
  venueUTCOffset: string;
  tvBroadcasts: IDailyScoresByDateOutput_games_tvBroadcasts[];
  gameState: string;
  gameScheduleState: string;
  awayTeam: IDailyScoresByDateOutput_games_awayTeam;
  homeTeam: IDailyScoresByDateOutput_games_awayTeam;
  gameCenterLink: string;
  threeMinRecap: string;
  condensedGame?: string;
  clock: IDailyScoresByDateOutput_games_clock;
  neutralSite: boolean;
  venueTimezone: string;
  period: number;
  periodDescriptor: IDailyScoresByDateOutput_games_periodDescriptor;
  gameOutcome: IDailyScoresByDateOutput_games_gameOutcome;
  goals: IDailyScoresByDateOutput_games_goals[];
  threeMinRecapFr?: string;
  specialEvent?: IDailyScoresByDateOutput_games_specialEvent;
  specialEventLogoURL?: string;
}

export interface IDailyScoresByDateOutput {
  prevDate: string;
  currentDate: string;
  nextDate: string;
  gameWeek: IDailyScoresByDateOutput_gameWeek[];
  oddsPartners: IDailyScoresByDateOutput_oddsPartners[];
  games: IDailyScoresByDateOutput_games[];
}
